<a href="https://colab.research.google.com/github/sagargoel072005/machine-learning/blob/main/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/sample_data/Bank_Churn_Classification_Dataset.csv')
df.head(5)

# df.Gender = pd.to_numeric(df.Gender,errors='coerce')
# df.info()
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})
df.dropna(how='any',inplace=True)
df.drop('Unnamed: 0', axis=1, inplace=True)
print(df['Churn'].value_counts()/len(df)*100)
# df.info()

X = df.drop(['CustomerID','Churn'],axis=1)
Y = df.Churn.values
# print(X.columns)

# convert categorical feature into numerical - feature encoding
X = pd.get_dummies(X,columns=[ 'Contract','PaymentMethod'],drop_first=True) # If you have N categories → keep only (N-1)
# X.head(1)

# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25, random_state=42)

from imblearn.over_sampling import RandomOverSampler
oversampler = RandomOverSampler()
x_train_upsampled,y_train_upsampled = oversampler.fit_resample(X_train,Y_train)

# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(x_train_upsampled)
X_test_sc = sc.transform(X_test)
# print(X_train_sc)

# call the KNN Classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, weights='distance')

knn.fit(X_train_sc,y_train_upsampled)
y_pred = knn.predict(X_test_sc)
print(y_pred)
print(Y_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, y_pred))


from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy:", accuracy_score(Y_test, y_pred)*100)
print("Precision:", precision_score(Y_test, y_pred)*100)
print("Recall:", recall_score(Y_test, y_pred)*100)
print("F1 Score:", f1_score(Y_test, y_pred)*100)


# # DECISION TREE
# from sklearn.tree import DecisionTreeClassifier,plot_tree

# dt = DecisionTreeClassifier()
# dt.fit(X_train_sc,Y_train)
# y_pred_dt = dt.predict(X_test_sc)
# print(y_pred_dt)
# print(Y_test)

# print("Accuracy:", accuracy_score(Y_test, y_pred_dt)*100)
# print("Precision:", precision_score(Y_test, y_pred_dt)*100)
# print("Recall:", recall_score(Y_test, y_pred_dt)*100)
# print("F1 Score:", f1_score(Y_test, y_pred_dt)*100)

# plt.figure(figsize=(20,20))
# plot_tree(dt,filled=True,feature_names=X_train.columns,max_depth=5,class_names=True)
# plt.show()


# from sklearn.tree import export_graphviz
# import graphviz
# export_graphviz(dt,filled=True,out_file="tree.dot",feature_names=X_train.columns,max_depth=5,class_names=True,proportion=True,special_characters=True)

# with open('tree.dot') as f:
#   dot_graph = f.read()
# graph = graphviz.Source(dot_graph,format='png')
# graph

Churn
0    73.3
1    26.7
Name: count, dtype: float64
[1 1 0 ... 1 1 1]
[0 0 0 ... 0 1 0]
[[1128  720]
 [ 385  267]]
Accuracy: 55.800000000000004
Precision: 27.0516717325228
Recall: 40.95092024539878
F1 Score: 32.58084197681514


In [ ]:
# RANDOM FOREST CLASSIFIER
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=500)
rf.fit(X_train_sc,Y_train)
y_pred_rf = rf.predict(X_test_sc)
print(y_pred_rf)
print(Y_test)

print("Accuracy:", accuracy_score(Y_test, y_pred_rf)*100)
print("Precision:", precision_score(Y_test, y_pred_rf)*100)
print("Recall:", recall_score(Y_test, y_pred_rf)*100)
print("F1 Score:", f1_score(Y_test, y_pred_rf)*100)


[0 0 0 ... 0 0 1]
[0 0 0 ... 0 0 1]
Accuracy: 69.16
Precision: 26.373626373626376
Recall: 7.007299270072993
F1 Score: 11.072664359861593


In [ ]:
#  NAIVE BAYES CLASSIFIER

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

nb = GaussianNB()
nb.fit(X_train_sc, Y_train)
y_pred_nb = nb.predict(X_test_sc)

print("NAIVE BAYES RESULTS")
print("Accuracy:", accuracy_score(Y_test, y_pred_nb)*100)
print("Precision:", precision_score(Y_test, y_pred_nb)*100)
print("Recall:", recall_score(Y_test, y_pred_nb)*100)
print("F1 Score:", f1_score(Y_test, y_pred_nb)*100)

NAIVE BAYES RESULTS
Accuracy: 72.6
Precision: 0.0
Recall: 0.0
F1 Score: 0.0


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
# SUPPORT VECTOR MACHINE

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

svm = SVC(kernel='rbf',class_weight='balanced')  # try 'linear' also
svm.fit(X_train_sc, Y_train)

y_pred_svm = svm.predict(X_test_sc)

print("SVM RESULTS")
print("Accuracy:", accuracy_score(Y_test, y_pred_svm)*100)
print("Precision:", precision_score(Y_test, y_pred_svm)*100)
print("Recall:", recall_score(Y_test, y_pred_svm)*100)
print("F1 Score:", f1_score(Y_test, y_pred_svm)*100)

SVM RESULTS
Accuracy: 46.48
Precision: 27.055516514406186
Recall: 56.20437956204379
F1 Score: 36.527514231499055


In [ ]:
# LOGISTIC REGRESSION CLASSIFIER

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

lr = LogisticRegression(max_iter=1000,class_weight='balanced')
lr.fit(X_train_sc, Y_train)

y_pred_lr = lr.predict(X_test_sc)

print("LOGISTIC REGRESSION RESULTS")
print("Accuracy:", accuracy_score(Y_test, y_pred_lr)*100)
print("Precision:", precision_score(Y_test, y_pred_lr)*100)
print("Recall:", recall_score(Y_test, y_pred_lr)*100)
print("F1 Score:", f1_score(Y_test, y_pred_lr)*100)

LOGISTIC REGRESSION RESULTS
Accuracy: 48.88
Precision: 26.184738955823295
Recall: 47.59124087591241
F1 Score: 33.78238341968912


In [ ]:
print("\nMODEL COMPARISON")
print("KNN Accuracy:", accuracy_score(Y_test, y_pred)*100)
print("DT Accuracy:", accuracy_score(Y_test, y_pred_dt)*100)
print("NB Accuracy:", accuracy_score(Y_test, y_pred_nb)*100)
print("SVM Accuracy:", accuracy_score(Y_test, y_pred_svm)*100)
print("LR Accuracy:", accuracy_score(Y_test, y_pred_lr)*100)


MODEL COMPARISON
KNN Accuracy: 66.0
DT Accuracy: 59.31999999999999
NB Accuracy: 72.6
SVM Accuracy: 46.48
LR Accuracy: 48.88


In [ ]:
# # KNN
# Accuracy: 66.0
# Precision: 28.34
# Recall: 15.76
# F1 Score: 20.26

# # DECISION TREE
# Accuracy: 59.31
# Precision: 26.14
# Recall: 26.56
# F1 Score: 26.35

# # random forest
# Accuracy: 69.32
# Precision: 27.47
# Recall: 7.29
# F1 Score: 11.53

# # SVM RESULTS
# Accuracy: 46.48
# Precision: 27.05
# Recall: 56.20
# F1 Score: 36.52

# # LOGISTIC REGRESSION RESULTS
# Accuracy: 48.88
# Precision: 26.18
# Recall: 47.59
# F1 Score: 33.78